/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/dialogs/AlertDialog.vue')['default']
    AppAutocomplete: typeof import('./src/@core/components/app-form-elements/AppAutocomplete.vue')['default']
    AppDateTimePicker: typeof import('./src/@core/components/app-form-elements/AppDateTimePicker.vue')['default']
    AppLoadingIndicator: typeof import('./src/components/AppLoadingIndicator.vue')['default']
    AppSelect: typeof import('./src/@core/components/app-form-elements/AppSelect.vue')['default']
    AppTextarea: typeof import('./src/@core/components/app-form-elements/AppTextarea.vue')['default']
    AppTextField: typeof import('./src/@core/components/app-form-elements/AppTextField.vue')['default']
    CashRegistersForm: typeof import('./src/components/cash registers/CashRegistersForm.vue')['default']
    CashRegistersGragh: typeof import('./src/components/cash registers/CashRegistersGragh.vue')['default']
    CashRegisterStats: typeof import('./src/components/cash registers/CashRegisterStats.vue')['default']
    CashRegisterUser: typeof import('./src/components/users/CashRegisterUser.vue')['default']
    ClientAppexDonutChart: typeof import('./src/components/clients/ClientAppexDonutChart.vue')['default']
    ClientForm: typeof import('./src/components/clients/ClientForm.vue')['default']
    ClientTypeGraph: typeof import('./src/components/clients/ClientTypeGraph.vue')['default']
    ConfirmDialog: typeof import('./src/components/dialogs/ConfirmDialog.vue')['default']
    ContactsForm: typeof import('./src/components/contacts/ContactsForm.vue')['default']
    DialogCloseBtn: typeof import('./src/@core/components/DialogCloseBtn.vue')['default']
    DocumentLogs: typeof import('./src/components/logs/DocumentLogs.vue')['default']
    DocumentLogsPreview: typeof import('./src/components/logs/DocumentLogsPreview.vue')['default']
    DocumentPreview: typeof import('./src/components/documents/DocumentPreview.vue')['default']
    DocumentPreviewContent: typeof import('./src/components/documents/DocumentPreviewContent.vue')['default']
    DocumentsEditable: typeof import('./src/components/documents/DocumentsEditable.vue')['default']
    DocumentsFooter: typeof import('./src/components/DocumentsFooter.vue')['default']
    DocumentsItems: typeof import('./src/components/documents/DocumentsItems.vue')['default']
    DocumentTable: typeof import('./src/components/documents/DocumentTable.vue')['default']
    I18n: typeof import('./src/@core/components/I18n.vue')['default']
    ListCashRegistersCard: typeof import('./src/components/cash registers/ListCashRegistersCard.vue')['default']
    ModalForm: typeof import('./src/components/ModalForm.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PaymentAppexDonutChart: typeof import('./src/components/payments/PaymentAppexDonutChart.vue')['default']
    PaymentForm: typeof import('./src/components/payments/PaymentForm.vue')['default']
    PaymentStatsGraph: typeof import('./src/components/payments/PaymentStatsGraph.vue')['default']
    PaymentTopSixActivitySectors: typeof import('./src/components/payments/PaymentTopSixActivitySectors.vue')['default']
    PaymentTopSixCities: typeof import('./src/components/payments/PaymentTopSixCities.vue')['default']
    PaymentTopSixClients: typeof import('./src/components/payments/PaymentTopSixClients.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./src/@core/components/ScrollToTop.vue')['default']
    SnackBar: typeof import('./src/components/SnackBar.vue')['default']
    TablePagination: typeof import('./src/@core/components/TablePagination.vue')['default']
    TiptapEditor: typeof import('./src/@core/components/TiptapEditor.vue')['default']
    TransactionForm: typeof import('./src/components/transactions/TransactionForm.vue')['default']
    UserCashRegister: typeof import('./src/components/users/UserCashRegister.vue')['default']
    UserForm: typeof import('./src/components/users/UserForm.vue')['default']
    UserRole: typeof import('./src/components/users/UserRole.vue')['default']
    VDateTimePicker: typeof import('./src/@core/components/app-form-elements/VDateTimePicker.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
