/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'archives-cashregisters': RouteRecordInfo<'archives-cashregisters', '/archives/cashregisters', Record<never, never>, Record<never, never>>,
    'archives-clients': RouteRecordInfo<'archives-clients', '/archives/clients', Record<never, never>, Record<never, never>>,
    'archives-clients-id': RouteRecordInfo<'archives-clients-id', '/archives/clients/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-documents-deliverynotes': RouteRecordInfo<'archives-documents-deliverynotes', '/archives/documents/deliverynotes', Record<never, never>, Record<never, never>>,
    'archives-documents-deliverynotes-id': RouteRecordInfo<'archives-documents-deliverynotes-id', '/archives/documents/deliverynotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-documents-invoicecredits': RouteRecordInfo<'archives-documents-invoicecredits', '/archives/documents/invoicecredits', Record<never, never>, Record<never, never>>,
    'archives-documents-invoicecredits-id': RouteRecordInfo<'archives-documents-invoicecredits-id', '/archives/documents/invoicecredits/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-documents-invoices': RouteRecordInfo<'archives-documents-invoices', '/archives/documents/invoices', Record<never, never>, Record<never, never>>,
    'archives-documents-invoices-id': RouteRecordInfo<'archives-documents-invoices-id', '/archives/documents/invoices/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-documents-ordernotes': RouteRecordInfo<'archives-documents-ordernotes', '/archives/documents/ordernotes', Record<never, never>, Record<never, never>>,
    'archives-documents-ordernotes-id': RouteRecordInfo<'archives-documents-ordernotes-id', '/archives/documents/ordernotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-documents-orderreceipts': RouteRecordInfo<'archives-documents-orderreceipts', '/archives/documents/orderreceipts', Record<never, never>, Record<never, never>>,
    'archives-documents-orderreceipts-id': RouteRecordInfo<'archives-documents-orderreceipts-id', '/archives/documents/orderreceipts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-documents-outputnotes': RouteRecordInfo<'archives-documents-outputnotes', '/archives/documents/outputnotes', Record<never, never>, Record<never, never>>,
    'archives-documents-outputnotes-id': RouteRecordInfo<'archives-documents-outputnotes-id', '/archives/documents/outputnotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-documents-productionnotes': RouteRecordInfo<'archives-documents-productionnotes', '/archives/documents/productionnotes', Record<never, never>, Record<never, never>>,
    'archives-documents-productionnotes-id': RouteRecordInfo<'archives-documents-productionnotes-id', '/archives/documents/productionnotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-documents-quoterequests': RouteRecordInfo<'archives-documents-quoterequests', '/archives/documents/quoterequests', Record<never, never>, Record<never, never>>,
    'archives-documents-quoterequests-id': RouteRecordInfo<'archives-documents-quoterequests-id', '/archives/documents/quoterequests/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-documents-quotes': RouteRecordInfo<'archives-documents-quotes', '/archives/documents/quotes', Record<never, never>, Record<never, never>>,
    'archives-documents-quotes-id': RouteRecordInfo<'archives-documents-quotes-id', '/archives/documents/quotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-documents-refunds': RouteRecordInfo<'archives-documents-refunds', '/archives/documents/refunds', Record<never, never>, Record<never, never>>,
    'archives-documents-refunds-id': RouteRecordInfo<'archives-documents-refunds-id', '/archives/documents/refunds/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-documents-returnnotes': RouteRecordInfo<'archives-documents-returnnotes', '/archives/documents/returnnotes', Record<never, never>, Record<never, never>>,
    'archives-documents-returnnotes-id': RouteRecordInfo<'archives-documents-returnnotes-id', '/archives/documents/returnnotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-payments': RouteRecordInfo<'archives-payments', '/archives/payments', Record<never, never>, Record<never, never>>,
    'archives-payments-id': RouteRecordInfo<'archives-payments-id', '/archives/payments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'archives-users': RouteRecordInfo<'archives-users', '/archives/users', Record<never, never>, Record<never, never>>,
    'archives-users-id': RouteRecordInfo<'archives-users-id', '/archives/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'cashregisters': RouteRecordInfo<'cashregisters', '/cashregisters', Record<never, never>, Record<never, never>>,
    'clients': RouteRecordInfo<'clients', '/clients', Record<never, never>, Record<never, never>>,
    'clients-id': RouteRecordInfo<'clients-id', '/clients/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-deliverynotes': RouteRecordInfo<'documents-deliverynotes', '/documents/deliverynotes', Record<never, never>, Record<never, never>>,
    'documents-deliverynotes-id': RouteRecordInfo<'documents-deliverynotes-id', '/documents/deliverynotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-deliverynotes-form': RouteRecordInfo<'documents-deliverynotes-form', '/documents/deliverynotes/form', Record<never, never>, Record<never, never>>,
    'documents-invoicecredits': RouteRecordInfo<'documents-invoicecredits', '/documents/invoicecredits', Record<never, never>, Record<never, never>>,
    'documents-invoicecredits-id': RouteRecordInfo<'documents-invoicecredits-id', '/documents/invoicecredits/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-invoicecredits-form': RouteRecordInfo<'documents-invoicecredits-form', '/documents/invoicecredits/form', Record<never, never>, Record<never, never>>,
    'documents-invoices': RouteRecordInfo<'documents-invoices', '/documents/invoices', Record<never, never>, Record<never, never>>,
    'documents-invoices-id': RouteRecordInfo<'documents-invoices-id', '/documents/invoices/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-invoices-form': RouteRecordInfo<'documents-invoices-form', '/documents/invoices/form', Record<never, never>, Record<never, never>>,
    'documents-ordernotes': RouteRecordInfo<'documents-ordernotes', '/documents/ordernotes', Record<never, never>, Record<never, never>>,
    'documents-ordernotes-id': RouteRecordInfo<'documents-ordernotes-id', '/documents/ordernotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-ordernotes-form': RouteRecordInfo<'documents-ordernotes-form', '/documents/ordernotes/form', Record<never, never>, Record<never, never>>,
    'documents-orderreceipt': RouteRecordInfo<'documents-orderreceipt', '/documents/orderreceipt', Record<never, never>, Record<never, never>>,
    'documents-orderreceipt-id': RouteRecordInfo<'documents-orderreceipt-id', '/documents/orderreceipt/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-orderreceipt-form': RouteRecordInfo<'documents-orderreceipt-form', '/documents/orderreceipt/form', Record<never, never>, Record<never, never>>,
    'documents-outputnotes': RouteRecordInfo<'documents-outputnotes', '/documents/outputnotes', Record<never, never>, Record<never, never>>,
    'documents-outputnotes-id': RouteRecordInfo<'documents-outputnotes-id', '/documents/outputnotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-outputnotes-form': RouteRecordInfo<'documents-outputnotes-form', '/documents/outputnotes/form', Record<never, never>, Record<never, never>>,
    'documents-productionnotes': RouteRecordInfo<'documents-productionnotes', '/documents/productionnotes', Record<never, never>, Record<never, never>>,
    'documents-productionnotes-id': RouteRecordInfo<'documents-productionnotes-id', '/documents/productionnotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-productionnotes-form': RouteRecordInfo<'documents-productionnotes-form', '/documents/productionnotes/form', Record<never, never>, Record<never, never>>,
    'documents-quoterequests': RouteRecordInfo<'documents-quoterequests', '/documents/quoterequests', Record<never, never>, Record<never, never>>,
    'documents-quoterequests-id': RouteRecordInfo<'documents-quoterequests-id', '/documents/quoterequests/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-quoterequests-form': RouteRecordInfo<'documents-quoterequests-form', '/documents/quoterequests/form', Record<never, never>, Record<never, never>>,
    'documents-quotes': RouteRecordInfo<'documents-quotes', '/documents/quotes', Record<never, never>, Record<never, never>>,
    'documents-quotes-id': RouteRecordInfo<'documents-quotes-id', '/documents/quotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-quotes-form': RouteRecordInfo<'documents-quotes-form', '/documents/quotes/form', Record<never, never>, Record<never, never>>,
    'documents-refunds': RouteRecordInfo<'documents-refunds', '/documents/refunds', Record<never, never>, Record<never, never>>,
    'documents-refunds-id': RouteRecordInfo<'documents-refunds-id', '/documents/refunds/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-refunds-form': RouteRecordInfo<'documents-refunds-form', '/documents/refunds/form', Record<never, never>, Record<never, never>>,
    'documents-returnnotes': RouteRecordInfo<'documents-returnnotes', '/documents/returnnotes', Record<never, never>, Record<never, never>>,
    'documents-returnnotes-id': RouteRecordInfo<'documents-returnnotes-id', '/documents/returnnotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'documents-returnnotes-form': RouteRecordInfo<'documents-returnnotes-form', '/documents/returnnotes/form', Record<never, never>, Record<never, never>>,
    'email': RouteRecordInfo<'email', '/email', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'logs-clients': RouteRecordInfo<'logs-clients', '/logs/clients', Record<never, never>, Record<never, never>>,
    'logs-clients-id': RouteRecordInfo<'logs-clients-id', '/logs/clients/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-contacts': RouteRecordInfo<'logs-contacts', '/logs/contacts', Record<never, never>, Record<never, never>>,
    'logs-contacts-id': RouteRecordInfo<'logs-contacts-id', '/logs/contacts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-documents-deliverynotes': RouteRecordInfo<'logs-documents-deliverynotes', '/logs/documents/deliverynotes', Record<never, never>, Record<never, never>>,
    'logs-documents-deliverynotes-id': RouteRecordInfo<'logs-documents-deliverynotes-id', '/logs/documents/deliverynotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-documents-invoicecredits': RouteRecordInfo<'logs-documents-invoicecredits', '/logs/documents/invoicecredits', Record<never, never>, Record<never, never>>,
    'logs-documents-invoicecredits-id': RouteRecordInfo<'logs-documents-invoicecredits-id', '/logs/documents/invoicecredits/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-documents-invoices': RouteRecordInfo<'logs-documents-invoices', '/logs/documents/invoices', Record<never, never>, Record<never, never>>,
    'logs-documents-invoices-id': RouteRecordInfo<'logs-documents-invoices-id', '/logs/documents/invoices/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-documents-ordernotes': RouteRecordInfo<'logs-documents-ordernotes', '/logs/documents/ordernotes', Record<never, never>, Record<never, never>>,
    'logs-documents-ordernotes-id': RouteRecordInfo<'logs-documents-ordernotes-id', '/logs/documents/ordernotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-documents-orderreceipts': RouteRecordInfo<'logs-documents-orderreceipts', '/logs/documents/orderreceipts', Record<never, never>, Record<never, never>>,
    'logs-documents-orderreceipts-id': RouteRecordInfo<'logs-documents-orderreceipts-id', '/logs/documents/orderreceipts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-documents-outputnotes': RouteRecordInfo<'logs-documents-outputnotes', '/logs/documents/outputnotes', Record<never, never>, Record<never, never>>,
    'logs-documents-outputnotes-id': RouteRecordInfo<'logs-documents-outputnotes-id', '/logs/documents/outputnotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-documents-productionnotes': RouteRecordInfo<'logs-documents-productionnotes', '/logs/documents/productionnotes', Record<never, never>, Record<never, never>>,
    'logs-documents-productionnotes-id': RouteRecordInfo<'logs-documents-productionnotes-id', '/logs/documents/productionnotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-documents-quoterequests': RouteRecordInfo<'logs-documents-quoterequests', '/logs/documents/quoterequests', Record<never, never>, Record<never, never>>,
    'logs-documents-quoterequests-id': RouteRecordInfo<'logs-documents-quoterequests-id', '/logs/documents/quoterequests/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-documents-quotes': RouteRecordInfo<'logs-documents-quotes', '/logs/documents/quotes', Record<never, never>, Record<never, never>>,
    'logs-documents-quotes-id': RouteRecordInfo<'logs-documents-quotes-id', '/logs/documents/quotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-documents-refunds': RouteRecordInfo<'logs-documents-refunds', '/logs/documents/refunds', Record<never, never>, Record<never, never>>,
    'logs-documents-refunds-id': RouteRecordInfo<'logs-documents-refunds-id', '/logs/documents/refunds/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-documents-returnnotes': RouteRecordInfo<'logs-documents-returnnotes', '/logs/documents/returnnotes', Record<never, never>, Record<never, never>>,
    'logs-documents-returnnotes-id': RouteRecordInfo<'logs-documents-returnnotes-id', '/logs/documents/returnnotes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-payments': RouteRecordInfo<'logs-payments', '/logs/payments', Record<never, never>, Record<never, never>>,
    'logs-payments-id': RouteRecordInfo<'logs-payments-id', '/logs/payments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-transactions': RouteRecordInfo<'logs-transactions', '/logs/transactions', Record<never, never>, Record<never, never>>,
    'logs-transactions-id': RouteRecordInfo<'logs-transactions-id', '/logs/transactions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'logs-users': RouteRecordInfo<'logs-users', '/logs/users', Record<never, never>, Record<never, never>>,
    'logs-users-id': RouteRecordInfo<'logs-users-id', '/logs/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'payments': RouteRecordInfo<'payments', '/payments', Record<never, never>, Record<never, never>>,
    'profil-id': RouteRecordInfo<'profil-id', '/profil/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'users-id': RouteRecordInfo<'users-id', '/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
